apiVersion: 1

datasources:
  - name: Elasticsearch Logs
    uid: mip-elasticsearch-logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: false
    editable: false
    jsonData:
      esVersion: 80
      interval: Daily
      timeField: timestamp
      logMessageField: event
      logLevelField: level

  - name: Druid HTTP
    uid: mip-druid-http
    type: marcusolsson-json-datasource
    access: proxy
    url: http://druid:8888/druid/v2/sql
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      maxResponseBodySize: 1048576
      timeout: 60
